name: evacuation-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - scikit-image
  - pillow
  - imageio
  - tqdm
  - seaborn
  - scikit-learn
  - numba
  - ipykernel
  - ipywidgets
  - pip
  - pip:
    - imageio-ffmpeg
    - celluloid
    - matplotlib-scalebar
    - pygame-ce
    - pygame_gui

